package finance

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/pg-cashflow/pg-go/internal/domain"
)

// Accounting Design Note: Collection-Basis (Cash-Basis) Revenue Recognition
// --------------------------------------------------------------------------
// This accounting subsystem deliberately operates on a modified collection basis
// rather than full accrual accounting:
// 1. Due Creation: When rent/utility dues are generated by billing cycles or manual entry,
//    no double-entry journal lines are created. Revenue is NOT recognized at invoice time.
// 2. Collection Recognition: Revenue (AcctRentRevenue, AcctUtilityRecoveryRevenue) is recognized
//    strictly upon payment receipt (MirrorPayment) when cash/bank/gateway clearing is debited.
// 3. Deposit Liability: Security deposits credit AcctDepositLiability (balance sheet liability)
//    and debit cash/bank/gateway clearing; deposits are never treated as operating revenue.
// 4. Tenant Receivable (AcctTenantReceivable): Not debited at due creation. It is only utilized
//    during departure settlement balancing (MirrorDepartureSettlement) when outstanding unpaid
//    dues are netted against deposit liabilities, during proration downward (MirrorProrateDue),
//    or when tenant credit balance is applied against due items (MirrorApplyCredit).
// --------------------------------------------------------------------------

type PaymentAllocationItem struct {
	AmountPaise int64
	DueKind     domain.DueKind
}

type RefundAllocationItem struct {
	AmountPaise int64
	DueKind     domain.DueKind
}

// MirrorPayment posts collection journal lines. Rent is recognized on collection.
func (s *Service) MirrorPayment(ctx context.Context, p *domain.Payment, due *domain.Due) error {
	if s == nil || s.Store == nil || p == nil || due == nil {
		return nil
	}
	amt := int64(p.Amount)
	if amt <= 0 {
		return nil
	}
	return s.MirrorPaymentAllocations(ctx, due.PropertyID, p, []PaymentAllocationItem{
		{AmountPaise: amt, DueKind: due.Kind},
	}, 0)
}

// MirrorPaymentAllocations posts collection journal lines broken down across dues and unapplied credits.
func (s *Service) MirrorPaymentAllocations(ctx context.Context, propertyID uuid.UUID, p *domain.Payment, allocations []PaymentAllocationItem, unappliedPaise int64) error {
	if s == nil || s.Store == nil || p == nil {
		return nil
	}
	totalAmt := int64(p.Amount)
	if totalAmt <= 0 {
		return nil
	}
	at := p.MatchedAt
	if at.IsZero() {
		at = s.Now()
	}
	cashAcct := domain.AcctBank
	if p.MatchedBy == domain.MatchedByCash {
		cashAcct = domain.AcctCash
	} else if p.MatchedBy == domain.MatchedByCashfree {
		cashAcct = domain.AcctGatewayClearing
	}

	accountTotals := make(map[string]int64)
	for _, a := range allocations {
		if a.AmountPaise <= 0 {
			continue
		}
		var crAccount string
		switch a.DueKind {
		case domain.DueKindDeposit:
			crAccount = domain.AcctDepositLiability
		case domain.DueKindElectricity, domain.DueKindWater:
			crAccount = domain.AcctUtilityRecoveryRevenue
		default:
			crAccount = domain.AcctRentRevenue
		}
		accountTotals[crAccount] += a.AmountPaise
	}
	if unappliedPaise > 0 {
		accountTotals[domain.AcctUnappliedReceipts] += unappliedPaise
	}

	specs := make([]LineSpec, 0, len(accountTotals)+1)
	specs = append(specs, LineSpec{
		Account:  cashAcct,
		Debit:    totalAmt,
		LineKind: "cash_in",
	})

	for acct, amt := range accountTotals {
		lineKind := "rent_collected"
		switch acct {
		case domain.AcctDepositLiability:
			lineKind = "deposit_liability"
		case domain.AcctUtilityRecoveryRevenue:
			lineKind = "utility_recovery"
		case domain.AcctUnappliedReceipts:
			lineKind = "unapplied_receipt"
		}
		specs = append(specs, LineSpec{
			Account:  acct,
			Credit:   amt,
			LineKind: lineKind,
		})
	}

	lines, err := MakeLines(propertyID, p.ID, "payment", at, specs)
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

// MirrorUnappliedPayment posts unapplied payment lines: Dr gateway_clearing, Cr unapplied_receipts.
func (s *Service) MirrorUnappliedPayment(ctx context.Context, propertyID, paymentID uuid.UUID, amountPaise int64, at time.Time) error {
	if s == nil || s.Store == nil || amountPaise <= 0 {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}
	lines, err := MakeLines(propertyID, paymentID, "unapplied_payment", at, []LineSpec{
		{Account: domain.AcctGatewayClearing, Debit: amountPaise, LineKind: "gateway_clearing_dr"},
		{Account: domain.AcctUnappliedReceipts, Credit: amountPaise, LineKind: "unapplied_receipt_cr"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

// MirrorRefund posts refund reversal lines: Dr unapplied_receipts/rent_revenue/deposit_liability, Cr gateway_clearing.
func (s *Service) MirrorRefund(ctx context.Context, propertyID, refundID uuid.UUID, amountPaise int64, isUnapplied bool, dueKind domain.DueKind, at time.Time) error {
	if s == nil || s.Store == nil || amountPaise <= 0 {
		return nil
	}
	if isUnapplied {
		if at.IsZero() {
			at = s.Now()
		}
		lines, err := MakeLines(propertyID, refundID, "refund", at, []LineSpec{
			{Account: domain.AcctUnappliedReceipts, Debit: amountPaise, LineKind: "refund_reversal_dr"},
			{Account: domain.AcctGatewayClearing, Credit: amountPaise, LineKind: "gateway_clearing_cr"},
		})
		if err != nil {
			return err
		}
		err = s.Store.InsertJournal(ctx, lines)
		if err == ErrDuplicateIdempotency {
			return nil
		}
		return err
	}
	return s.MirrorRefundAllocations(ctx, propertyID, refundID, []RefundAllocationItem{
		{AmountPaise: amountPaise, DueKind: dueKind},
	}, at)
}

// MirrorRefundAllocations aggregates multiple refund allocations by account and posts a single balanced journal entry.
func (s *Service) MirrorRefundAllocations(ctx context.Context, propertyID, refundID uuid.UUID, allocations []RefundAllocationItem, at time.Time) error {
	if s == nil || s.Store == nil || len(allocations) == 0 {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}
	accountTotals := make(map[string]int64)
	var totalPaise int64
	for _, a := range allocations {
		if a.AmountPaise <= 0 {
			continue
		}
		var drAccount string
		switch a.DueKind {
		case domain.DueKindDeposit:
			drAccount = domain.AcctDepositLiability
		case domain.DueKindElectricity, domain.DueKindWater:
			drAccount = domain.AcctUtilityRecoveryRevenue
		default:
			drAccount = domain.AcctRentRevenue
		}
		accountTotals[drAccount] += a.AmountPaise
		totalPaise += a.AmountPaise
	}
	if totalPaise <= 0 {
		return nil
	}

	specs := make([]LineSpec, 0, len(accountTotals)+1)
	if len(accountTotals) == 1 {
		for acct, amt := range accountTotals {
			specs = append(specs, LineSpec{
				Account:  acct,
				Debit:    amt,
				LineKind: "refund_reversal_dr",
			})
		}
	} else {
		for acct, amt := range accountTotals {
			lineKind := "refund_reversal_dr"
			switch acct {
			case domain.AcctDepositLiability:
				lineKind = "refund_reversal_deposit_dr"
			case domain.AcctUtilityRecoveryRevenue:
				lineKind = "refund_reversal_utility_dr"
			case domain.AcctRentRevenue:
				lineKind = "refund_reversal_rent_dr"
			case domain.AcctUnappliedReceipts:
				lineKind = "refund_reversal_unapplied_dr"
			}
			specs = append(specs, LineSpec{
				Account:  acct,
				Debit:    amt,
				LineKind: lineKind,
			})
		}
	}
	specs = append(specs, LineSpec{
		Account:  domain.AcctGatewayClearing,
		Credit:   totalPaise,
		LineKind: "gateway_clearing_cr",
	})

	lines, err := MakeLines(propertyID, refundID, "refund", at, specs)
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

func (s *Service) MirrorProration(ctx context.Context, due *domain.Due, original, prorated int64) error {
	if s == nil || due == nil {
		return nil
	}
	// Under collection-basis (cash-basis) revenue recognition, unpaid dues have never
	// had journal lines or revenue recognized. Prorating an open/unpaid due requires
	// no ledger lines, preventing artificial negative revenue and unbacked receivable credits.
	if due.Status != domain.DueStatusPaid && due.Status != domain.DueStatusPartial {
		return nil
	}
	diff := original - prorated
	if diff <= 0 {
		return nil
	}
	lines, err := MakeLines(due.PropertyID, due.ID, "proration", s.Now(), []LineSpec{
		{Account: domain.AcctRentRevenue, Debit: diff, LineKind: "proration_dr"},
		{Account: domain.AcctTenantReceivable, Credit: diff, LineKind: "proration_cr"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

func (s *Service) MirrorApplyCredit(ctx context.Context, propertyID, dueID uuid.UUID, amountPaise int64, dueKind domain.DueKind, at time.Time) error {
	if s == nil || s.Store == nil || amountPaise <= 0 {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}
	var revAccount string
	switch dueKind {
	case domain.DueKindDeposit:
		revAccount = domain.AcctDepositLiability
	case domain.DueKindElectricity, domain.DueKindWater:
		revAccount = domain.AcctUtilityRecoveryRevenue
	default:
		revAccount = domain.AcctRentRevenue
	}
	lines, err := MakeLines(propertyID, dueID, "apply_credit", at, []LineSpec{
		{Account: domain.AcctTenantReceivable, Debit: amountPaise, LineKind: "credit_dr"},
		{Account: revAccount, Credit: amountPaise, LineKind: "revenue_cr"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

func (s *Service) MirrorRewardRedeem(ctx context.Context, propertyID, tenantID, redemptionID uuid.UUID, points int, amountPaise int64) error {
	if s == nil || amountPaise <= 0 {
		return nil
	}
	at := s.Now()
	txn := &domain.RewardLiabilityTxn{
		ID:          uuid.New(),
		PropertyID:  propertyID,
		TenantID:    &tenantID,
		Kind:        "redeemed",
		Points:      points,
		AmountPaise: amountPaise,
		SourceType:  "redemption",
		SourceID:    redemptionID,
		OccurredAt:  at,
	}
	if err := s.Store.InsertRewardLiability(ctx, txn); err != nil && err != ErrDuplicateIdempotency {
		return err
	}
	lines, err := MakeLines(propertyID, redemptionID, "reward_redeem", at, []LineSpec{
		{Account: domain.AcctRewardLiability, Debit: amountPaise, LineKind: "liability_release"},
		{Account: domain.AcctTenantReceivable, Credit: amountPaise, LineKind: "credit_applied"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

func (s *Service) MirrorPointsIssued(ctx context.Context, propertyID, tenantID, ledgerID uuid.UUID, points int, amountPaise int64) error {
	if s == nil || amountPaise <= 0 {
		return nil
	}
	at := s.Now()
	txn := &domain.RewardLiabilityTxn{
		ID:          uuid.New(),
		PropertyID:  propertyID,
		TenantID:    &tenantID,
		Kind:        "issued",
		Points:      points,
		AmountPaise: amountPaise,
		SourceType:  "points_ledger",
		SourceID:    ledgerID,
		OccurredAt:  at,
	}
	if err := s.Store.InsertRewardLiability(ctx, txn); err != nil && err != ErrDuplicateIdempotency {
		return err
	}
	lines, err := MakeLines(propertyID, ledgerID, "reward_issue", at, []LineSpec{
		{Account: domain.AcctLoyaltyExpense, Debit: amountPaise, LineKind: "loyalty_dr"},
		{Account: domain.AcctRewardLiability, Credit: amountPaise, LineKind: "liability_cr"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

func (s *Service) SuggestCSVDebit(ctx context.Context, propertyID uuid.UUID, txnID string, amount int, date time.Time, note string) error {
	sug := &domain.ExpenseImportSuggestion{
		PropertyID:  propertyID,
		TxnID:       txnID,
		AmountPaise: int64(amount),
		TxnDate:     date,
		Note:        note,
		Status:      "pending",
	}
	return s.Store.UpsertImportSuggestion(ctx, sug)
}

// MirrorDepartureSettlement posts balanced journal entries for tenant departure settlement:
// Dr deposit_liability (depositPaise)
// Dr rent_revenue (unusedRentReversal, if > 0)
// Dr tenant_receivable (receivableBalancePaise, if > 0)
// Cr rent_revenue (outstandingDuesNettedPaise, if unpaid cycle or prorated dues netted from deposit)
// Cr damages_income (damagesPaise, if > 0)
// Cr refund_payable (netRefundPaise, if > 0)
func (s *Service) MirrorDepartureSettlement(
	ctx context.Context,
	propertyID, departureID uuid.UUID,
	depositPaise, unusedRentReversal, damagesPaise, netRefundPaise, outstandingDuesNettedPaise, receivableBalancePaise int64,
	at time.Time,
) error {
	if s == nil || s.Store == nil {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}

	var specs []LineSpec
	if depositPaise > 0 {
		specs = append(specs, LineSpec{Account: domain.AcctDepositLiability, Debit: depositPaise, LineKind: "deposit_release"})
	}
	if unusedRentReversal > 0 {
		specs = append(specs, LineSpec{Account: domain.AcctRentRevenue, Debit: unusedRentReversal, LineKind: "unearned_rent_reversal"})
	}
	if receivableBalancePaise > 0 {
		specs = append(specs, LineSpec{Account: domain.AcctTenantReceivable, Debit: receivableBalancePaise, LineKind: "tenant_receivable"})
	}
	if outstandingDuesNettedPaise > 0 {
		specs = append(specs, LineSpec{Account: domain.AcctRentRevenue, Credit: outstandingDuesNettedPaise, LineKind: "dues_netted_earned"})
	}
	if damagesPaise > 0 {
		specs = append(specs, LineSpec{Account: domain.AcctDamagesIncome, Credit: damagesPaise, LineKind: "damages_recovery"})
	}
	if netRefundPaise > 0 {
		specs = append(specs, LineSpec{Account: domain.AcctRefundPayable, Credit: netRefundPaise, LineKind: "tenant_refund_payable"})
	}

	lines, err := MakeLines(propertyID, departureID, "departure_settlement", at, specs)
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

// MirrorPayoutSettled posts journal entry when a refund_payable payout item is settled from the bank account:
// Dr refund_payable (amountPaise)
// Cr bank (amountPaise)
func (s *Service) MirrorPayoutSettled(ctx context.Context, propertyID, payoutItemID uuid.UUID, amountPaise int64, at time.Time) error {
	if s == nil || s.Store == nil || amountPaise <= 0 {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}
	lines, err := MakeLines(propertyID, payoutItemID, "payout_settlement", at, []LineSpec{
		{Account: domain.AcctRefundPayable, Debit: amountPaise, LineKind: "refund_paid"},
		{Account: domain.AcctBank, Credit: amountPaise, LineKind: "cash_out"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

// MirrorPayoutReversed posts journal entry when a previously settled payout is reversed:
// Dr bank (amountPaise)
// Cr refund_payable (amountPaise)
func (s *Service) MirrorPayoutReversed(ctx context.Context, propertyID, payoutItemID uuid.UUID, amountPaise int64, at time.Time) error {
	if s == nil || s.Store == nil || amountPaise <= 0 {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}
	lines, err := MakeLines(propertyID, payoutItemID, "payout_reversal", at, []LineSpec{
		{Account: domain.AcctBank, Debit: amountPaise, LineKind: "cash_in"},
		{Account: domain.AcctRefundPayable, Credit: amountPaise, LineKind: "refund_reversal"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

// MirrorBankStatementCredit posts initial ingestion of cleared bank statement credit:
// Dr bank (amountPaise)
// Cr unapplied_receipts (amountPaise)
func (s *Service) MirrorBankStatementCredit(ctx context.Context, propertyID, bankTxnID uuid.UUID, amountPaise int64, at time.Time) error {
	if s == nil || s.Store == nil || amountPaise <= 0 {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}
	lines, err := MakeLines(propertyID, bankTxnID, "bank_statement_credit", at, []LineSpec{
		{Account: domain.AcctBank, Debit: amountPaise, LineKind: "bank_deposit_dr"},
		{Account: domain.AcctUnappliedReceipts, Credit: amountPaise, LineKind: "unapplied_receipt_cr"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

// MirrorUnappliedAllocation posts allocation of quarantined unapplied receipts to settled dues:
// Dr unapplied_receipts (amountPaise)
// Cr rent_revenue / deposit_liability / utility_recovery_revenue (amountPaise)
func (s *Service) MirrorUnappliedAllocation(ctx context.Context, propertyID, bankTxnID uuid.UUID, dueKind domain.DueKind, amountPaise int64, at time.Time) error {
	if s == nil || s.Store == nil || amountPaise <= 0 {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}
	var crAccount string
	switch dueKind {
	case domain.DueKindDeposit:
		crAccount = domain.AcctDepositLiability
	case domain.DueKindElectricity, domain.DueKindWater:
		crAccount = domain.AcctUtilityRecoveryRevenue
	default:
		crAccount = domain.AcctRentRevenue
	}
	lines, err := MakeLines(propertyID, bankTxnID, "unapplied_allocation", at, []LineSpec{
		{Account: domain.AcctUnappliedReceipts, Debit: amountPaise, LineKind: "unapplied_receipt_allocated_dr"},
		{Account: crAccount, Credit: amountPaise, LineKind: "due_earned_cr"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

// MirrorBankDepositRefund posts refund of unidentified bank deposit back to payer:
// Dr unapplied_receipts (amountPaise)
// Cr bank (amountPaise)
func (s *Service) MirrorBankDepositRefund(ctx context.Context, propertyID, bankTxnID uuid.UUID, amountPaise int64, at time.Time) error {
	if s == nil || s.Store == nil || amountPaise <= 0 {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}
	lines, err := MakeLines(propertyID, bankTxnID, "unapplied_deposit_refund", at, []LineSpec{
		{Account: domain.AcctUnappliedReceipts, Debit: amountPaise, LineKind: "unapplied_receipt_refund_dr"},
		{Account: domain.AcctBank, Credit: amountPaise, LineKind: "bank_refund_cr"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

// MirrorUnappliedReclassification posts reclassification of non-rent bank deposits:
// Dr unapplied_receipts (amountPaise)
// Cr interest_income / owner_capital / non_pg_other_income / operating_expense
func (s *Service) MirrorUnappliedReclassification(ctx context.Context, propertyID, bankTxnID uuid.UUID, targetAccount string, amountPaise int64, at time.Time) error {
	if s == nil || s.Store == nil || amountPaise <= 0 {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}
	if targetAccount == "" {
		targetAccount = domain.AcctNonPGOtherIncome
	}
	lines, err := MakeLines(propertyID, bankTxnID, "unapplied_reclassification", at, []LineSpec{
		{Account: domain.AcctUnappliedReceipts, Debit: amountPaise, LineKind: "unapplied_receipt_reclass_dr"},
		{Account: targetAccount, Credit: amountPaise, LineKind: "reclass_target_cr"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

// MirrorDepositSettlement posts deposit settlement lines:
// Dr deposit_liability (totalSettled)
// Cr cash/bank (refundedPaise)
// Cr rent_revenue (deductionsPaise)
func (s *Service) MirrorDepositSettlement(
	ctx context.Context,
	propertyID, settlementID, tenantID, dueID uuid.UUID,
	originalDepositPaise, refundedPaise, deductionsPaise int64,
	at time.Time,
) error {
	if s == nil || s.Store == nil {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}

	totalSettled := refundedPaise + deductionsPaise
	if totalSettled <= 0 {
		return nil
	}

	specs := make([]LineSpec, 0, 3)
	specs = append(specs, LineSpec{
		Account:  domain.AcctDepositLiability,
		Debit:    totalSettled,
		LineKind: "deposit_release",
	})
	if refundedPaise > 0 {
		specs = append(specs, LineSpec{
			Account:  domain.AcctCash,
			Credit:   refundedPaise,
			LineKind: "deposit_refund_cash",
		})
	}
	if deductionsPaise > 0 {
		specs = append(specs, LineSpec{
			Account:  domain.AcctRentRevenue,
			Credit:   deductionsPaise,
			LineKind: "damage_deduction",
		})
	}

	lines, err := MakeLines(propertyID, settlementID, "deposit_settlement", at, specs)
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}

// MirrorPaymentCorrection posts a reversing journal for the original payment.
func (s *Service) MirrorPaymentCorrection(
	ctx context.Context,
	propertyID, correctionID, originalPaymentID uuid.UUID,
	amountPaise int64,
	at time.Time,
) error {
	if s == nil || s.Store == nil || amountPaise <= 0 {
		return nil
	}
	if at.IsZero() {
		at = s.Now()
	}
	// Reversal: Dr rent_revenue, Cr cash/bank (reversing original collection)
	lines, err := MakeLines(propertyID, correctionID, "payment_correction", at, []LineSpec{
		{Account: domain.AcctRentRevenue, Debit: amountPaise, LineKind: "correction_reversal_dr"},
		{Account: domain.AcctCash, Credit: amountPaise, LineKind: "correction_reversal_cr"},
	})
	if err != nil {
		return err
	}
	err = s.Store.InsertJournal(ctx, lines)
	if err == ErrDuplicateIdempotency {
		return nil
	}
	return err
}
